### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by fabwu** [wuethrich44/zusammenfassung-aitec#12]

**Comment by alexsuter** [comment]
Es ist ein bisschen schwierig, da nicht viel Material vorhanden ist. Ich denke dass ich eigentlich genug zusammengefasst habe, bin mir aber nicht ganz sicher. Falls Du das Gefühl hast, dass noch irgendwas dokumentiert werden sollte - dann kannst Du mir einen Issue machen.

**Comment by fabwu** [comment]
:+1:

**Comment by alexsuter** [comment]
noch warten mit review, hier.

**Comment by alexsuter** [comment]
go

**Comment by alexsuter** [comment]
p.s. auf studendtbox hat es noch ein anki file für dieses modul.

**Comment by fabwu** [comment]
:+1:

**Comment by fabwu** [comment]
@alexsuter Ah heds funktioniert mitem account uf studentbox?

**Comment by alexsuter** [comment]
:+1:
