### ISSUE TITLE
Internet Trends

### ISSUE THREAD

**Issue by fabwu** [wuethrich44/zusammenfassung-aitec#9]

**Comment by fabwu** [comment]
@alexsuter Hast du den Arduino-Abschnitt gesehen?

**Comment by alexsuter** [comment]
@wuethrich44  Du redest von Kapitel 4 im Dokument 04 Internet Trends? Nein den habe ich nicht gesehen beim Dokumentieren. Ich werde bei diesem Review diesen Abschnitt noch ins Kapitel Arduino einbauen. Aber ich glaube das meiste habe ich schon drin (wiederholung).

**Comment by fabwu** [comment]
:+1:
